[package]
name = "slimevr-espnow-bridge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macaddr = "1.0.1"
tokio = { version = "1.35.1", features = ["full"] }
tokio-serial = "5.4.4"
